import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

serve(async (req) => {
  // 1. Handle CORS (so your frontend/friends can actually talk to this function)
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: { 'Access-Control-Allow-Origin': '*' } });
  }

  try {
    // 2. Catch the text generated by Friend 2's AI brain
    const { text } = await req.json();

    // 3. Grab your new ElevenLabs Key securely
    const elevenLabsApiKey = Deno.env.get("ELEVENLABS_API_KEY");
    
    // This is the Voice ID. (You can swap this later for an older-sounding voice from their library)
    const voiceId = "21m00Tcm4TlvDq8ikWAM"; 

    // 4. Send the request to ElevenLabs
    // Notice the "?output_format=ulaw_8000" in the URL - this is mandatory for Twilio phone calls!
    const response = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=ulaw_8000`, {
      method: "POST",
      headers: {
        "xi-api-key": elevenLabsApiKey!,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        text: text,
        model_id: "eleven_flash_v2_5", // The ultra-fast model so the scammer doesn't hang up waiting
        voice_settings: {
          stability: 0.3, // Low stability = more emotional, human, and slightly confused
          similarity_boost: 0.7,
          speed: 0.9      // Slightly slower speaking pace
        }
      }),
    });

    if (!response.ok) {
      throw new Error(`ElevenLabs Error: ${await response.text()}`);
    }

    // 5. Convert the response into raw audio data
    const audioBuffer = await response.arrayBuffer();

    // 6. Return the audio file directly back to Twilio to play to the scammer
    return new Response(audioBuffer, {
      headers: { 
        "Content-Type": "audio/basic", // This tells Twilio it's receiving phone-ready audio
        "Access-Control-Allow-Origin": "*" 
      },
    });

  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
});